name: Update Playlist

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */3 * * *"

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Build playlist
        run: |
          echo "#EXTM3U" > playlist.m3u

          urls=(
            "https://raw.githubusercontent.com/tropicx24-commits/my_channels.m3u/main/playlist.m3u"
            "https://raw.githubusercontent.com/batuhansabri55/AkcagozTV_Film/main/FilmDizi.m3u"
            "https://https://raw.githubusercontent.com/LITUATUI/M3UPT/refs/heads/main/M3U/TVI_Reality.m3u8"
          )

          i=1
          files=()

          for url in "${urls[@]}"; do
            echo "----------------------------------------"
            echo "Downloading: $url"

            if curl -L --fail "$url" -o "list$i.m3u"; then
              echo "OK"
              files+=("list$i.m3u")
              i=$((i+1))
            else
              echo "FAILED"
            fi
          done

          if [ ${#files[@]} -gt 0 ]; then
            awk '
            /^#EXTINF/{
                extinf=$0
                getline url
                gsub(/\r/,"",url)

                if(!seen[url]++){
                    print extinf
                    print url
                }
            }' "${files[@]}" >> playlist.m3u
          fi

          echo ""
          echo "Toplam kanal:"
          grep -c "^#EXTINF" playlist.m3u || true

          rm -f list*.m3u

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add playlist.m3u

          if git diff --staged --quiet; then
            echo "No changes"
          else
            git commit -m "Auto update playlist"
            git push
          fi
