name: Update Playlist

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */3 * * *"

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build playlist
        run: |
          curl -L "https://raw.githubusercontent.com/tropicx24-commits/my_channels.m3u/main/playlist.m3u" -o my_channels.m3u

          curl -L "https://raw.githubusercontent.com/batuhansabri55/AkcagozTV_Film/refs/heads/main/FilmDizi.m3u" -o remote.m3u

          curl -L "https://raw.githubusercontent.com/LITUATUI/M3UPT/refs/heads/main/M3U/TVI_Reality.m3u8
          
          echo "#EXTM3U" > playlist.m3u

          awk '
          /^#EXTINF/ {
              extinf=$0
              getline url

              if (!seen[url]++) {
                  print extinf
                  print url
              }
          }
          ' my_channels.m3u remote.m3u >> playlist.m3u

          rm -f my_channels.m3u remote.m3u

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add playlist.m3u

          if git diff --staged --quiet; then
            echo "No changes"
          else
            git commit -m "Auto update playlist"
            git push
          fi
